let nume = [
  "Eugen",
  "Belzebut",
  "Duţulache",
  "Og",
  "Ramses",
  "Ludovic",
  "Mihail",
  "Nicuşor",
  "Marieta",
  "Ana",
  "Darius",
  "Gerula",
  "Spartacus",
  "Nelu",
  "Leon",
  "Brunhilda",
  "Solomon",
  "Florinela",
  "Marcel",
  "Ştefănuţ",
  "Dumitru",
  "Zamfira",
  "Fram",
  "Mickey",
  "Sabrina",
  "Gigi",
  "Macaulay",
  "Miron",
  "Satoshi",
  "Ieremia",
  "Eudochia",
  "Ionela",
  "Elon",
  "Jeaneta",
  "Carmen",
  "Aureola",
  "Calistrat",
  "Duiliu",
  "Arsenie",
  "Geani",
  "Timotei",
  "Dalai",
  "Benone",
  "Tamara",
  "Răzvy",
  "Şobo",
  "Zorro",
  "Reginald",
  "Decebal",
];

let ocupatii = [
  "un puşti",
  "un demon",
  "un brontozaur",
  "un neanderthalian",
  "un faraon",
  "un principe",
  "un arhanghel",
  "un primar",
  "o fată",
  "o tipă",
  "un mititel",
  "un pui de dac",
  "un gladiator",
  "un domn",
  "un revoluţionar",
  "o vikingă",
  "un prichindel",
  "o copiliţă",
  "un ţânc",
  "un pezevenghi",
  "un plod",
  "o cuconiţă",
  "un urs polar",
  "un mouse",
  "o vrăjitoare",
  "un cioban",
  "un actor",
  "un vlăjgan",
  "un samurai",
  "un voievod",
  "o pramatie",
  "o persoană",
  "un magnat",
  "o fetiţă",
  "o puştoaică",
  "o copilă",
  "un holtei",
  "un june",
  "un băieţel",
  "un băieţaş",
  "un şampon",
  "un lama tibetan",
  "un interpret",
  "o mătuşică",
  "un cârlan",
  "un plăvan",
  "un dârlău",
  "un copilaş",
  "un muţunache",
];

let anotimpuri = [
  "iarnă",
  "Cretacic",
  "primăvară",
  "Jurasic",
  "vară",
  "toamnă",
  "ianuarie",
  "februarie",
  "an bisect",
  "Ev Mediu",
  "noiembrie",
  "iulnie sau poate noctombrie",
  "iunie",
  "iulie",
  "aprilie",
  "martie",
  "joi",
  "vacanţă",
  "sărbătoare",
  "decembrie",
  "Vărsător",
  "Mercur retrograd",
  "pandemie",
  "septembrie",
  "alaltăieri",
  "post-apocalipsă",
  "mai",
  "august",
  "1944",
  "Halloween",
  "Bobotează",
  "9000 î. e. n.",
];

let orase = [
  "Miercurea Nirajului",
  "Popeşti",
  "Berceni",
  "Rahova",
  "Pantelimon",
  "Titan",
  "Grojdibodu",
  "Fierbinţi",
  "Cluj",
  "Oradea",
  "Constanţa",
  "Iaşi",
  "Suceava",
  "Giurgiu",
  "Adunaţii Copăceni",
  "Scorniceşti",
  "Voluntari",
  "Craiova",
  "Timişoara",
  "Tecuci",
  "Băile Tuşnad",
  "Vârteşcoiu",
  "Băicoi",
  "Gurbăneşti",
  "Adjud",
  "Râmnicu Sărat",
  "Lugoj",
  "Deva",
  "Zalău",
  "Vama Veche",
  "Saturn",
  "Sovata",
  "Fundulea",
  "Zărneşti",
  "Braşov",
  "Galaţi",
  "Brăila",
  "Botoşani",
  "Dorohoi",
  "Fundu Moldovei",
  "Măciuca",
  "Mierleştii de Sus",
  "Udaţi-Mânzu",
  "Medgidia",
  "Beiuş",
  "Teiuş",
  "Curtici",
  "Şimleu Silvaniei",
  "Dolhasca",
  "Paşcani",
  "Caracal",
  "Târgu Jiu",
  "Târgu Mureş",
  "Curtea de Argeş",
  "Bran",
  "Slănic Prahova",
  "New Orleans",
  "Salonta",
  "Bronx",
  "Jakarta",
  "Comarnic",
  "Primăverii",
  "Colentina, inima străzii",
  "Buzău",
  "Focşani",
  "Oneşti",
  "Bacău",
  "Vaslui",
  "Huşi",
  "Bârlad",
  "Kathmandu",
  "Trebuci",
];

let rudenii = [
  "mama",
  "tatăl",
  "bunica",
  "bunicul",
  "geamănul malefic al",
  "străbunica",
  "străbunicul",
  "strămoşul",
  "învăţătoarea",
  "unchiul",
  "cuscrul",
  "mătuşa",
  "amanta tatălui",
  "şogorul vecinului",
  "îngerul păzitor al",
  "mama vitregă a",
  "tataia",
  "mamaia",
  "babacul",
  "născătoarea",
];

let probleme = [
  "copilului i-a căzut şapca în butoiul cu must",
  "la RTV au zis că ne invadează sexomarxiştii",
  "a rămas fisa blocată în căruciorul de la supermarket",
  "profa de franceză a făcut un sunet groaznic cu unghiile pe tablă",
  "americanii au înscenat aselenizarea la studiourile Buftea",
  "trupa Vunk a scos un album nou",
  "s-a pierdut Zdreanţă, cel cu ochii de faianţă",
  "ceilalţi copii au luat o notă mai mare la Educaţie Fizică",
  "nimeni nu se mai uită la MASH în zilele noastre",
  "cineva i-a dărâmat copilului îngheţata de pe cornet",
  "vandalii au desenat o mustaţă pe afişul preferat cu Bănică al copilului",
  "un pensionar şi-a agitat bastonul în direcţia lor",
  "aşa-zisul Moş de la serbare era de fapt un tânăr cu barbă falsă",
  "toţi cunoscuţii şi-au schimbat parola de la netflix",
  "clanurile interlope au pus stăpânire asupra oraşului",
  "asupra unor politicieni planează suspiciuni de corupţie",
  "persoane necunoscute au mâzgălit ceva urât despre Rapid pe un gard",
  "pe o maşină undeva în cartier scrie SPALĂ-MĂ",
  "un pescăruş rău le-a ciugulit cartofii proaspăt cumpăraţi de la Mec",
  "nişte derbedei au fumat marihuana şi au cântat la chitară în parc",
  "curierul a anunţat că vine între 9 şi 5 şi a venit la 6 jumate",
  "vecinii au dat un party cu trap şi manele ignorând orele de linişte",
  "un vecin le-a tăiat mingea copiilor",
  "o pisicuţă a urcat în pom şi le scrie mesaje de ameninţare",
  "un tigru bengalez a evadat de la grădina zoologică",
  "un beţiv a râgâit în tramvai",
  "doamna educatoare vinde marihuana pe darkweb",
  "în loc de 'Opriţi planeta' pe piesa lui Puya se înţelege 'Opriţi toaleta'",
  "buticul din gară vinde ţigări la bucată",
  "s-au terminat bateriile la maneta de la xbox",
  "hoţii au furat piticul din grădină",
  "cineva a ciupit muşamaua de pe masa din bucătărie",
  "profa de fizică ameninţă cu un extemporal",
  "vatmanul refuză să întoarcă tramvaiul",
  "ursuleţului Bobi i s-a descusut o ureche",
  "un pisoi s-a căţărat în stratosferă şi miaună sfâşietor",
  "consiliul judeţean a făcut o donaţie considerabilă pentru catedrală",
  "Twitter se cheamă acum X",
  "un vecin îşi repară Dacia foarte zgomotos în faţa blocului",
  "bibliotecara le-a cerut să aducă toate cărţile înapoi",
  "cineva a ciobit peştele de sticlă de pe TV",
  "cineva a mozolit faţa de masă cu ceea ce pare a fi nutella",
  "cineva a ucis 99% din bacteriile de pe colacul de WC",
  "cineva a pus bateriile de la telecomandă invers",
  "cineva a pufnit în râs la un parastas",
  "Ronald McDonald a refuzat să facă un căţel din baloane pentru că era în pauză",
  "preţul de la raft nu corespunde cu cel de la casă",
  "cineva a furat butonul de deschidere a uşilor din tramvai",
  "pe gardul casei a apărut un abţibild suspect",
  "un vecin le-a tăiat mingea copiilor",
  "raţele din parc au refuzat salata pentru că s-au învăţat cu pâine",
  "inflaţia galopantă a scumpit covrigul cu încă 50 de bani",
  "China a renunţat la politica copilului unic",
  "cineva dă cu bormaşina de jumătate de oră",
  "li s-a pus pastă de dinţi Aquafresh pe clanţă",
  "mama lui Ştefan cel Mare l-a alungat pe acesta de la poartă",
  "Milli Vanilli au făcut playback în anii 80",
  "cineva a deturnat banii de sendviş din offshore-ul din insulele Cayman al copilului",
  "cineva i-a suflat copilului un cornet în păr",
  "o lucrare de doctorat s-a dovedit a fi plagiată",
  "copilului i s-a lipit o gumă de mestecat de blugi",
  "Zâna Măseluţă i-a dat ţeapă copilului cu 4 lei",
  "copilul şi-a pierdut iPhoneul în reprezentanţa Louis Vuitton",
  "s-a băgat în selfie-ul copilului o persoană cu nasul mare",
  "temperatura medie a oceanelor a crescut cu 2 grade",
  "nimeni nu le-a explicat regulile jocului de bambilici",
  "de undeva din întuneric s-a auzit CUCU BAU",
  "hoţii deghizaţi în degete i-au furat copilului nasul",
  "colegul de bancă nu vrea să returneze ascuţitoarea împrumutată",
  "cineva a mâncat ultimul Eti Puf din cămară",
  "vocile au început să vorbească în aramaică",
  "cineva a dezinstalat Minecraft de pe xboxul din sufragerie",
  "o colegă are mai multe likeuri pe insta",
];

let rezolvari = [
  "deschis dosar penal pentru contrafacere de tenişi",
  "mâncat două cartoane de gogoşi de la Fiţoşica",
  "comandat două şaorme şi returnat una fiindcă avea pătrunjel",
  "compus un articol viral pentru pagina de Facebook",
  "apărat patru penalty-uri şi au câştigat Cupa Poliţiei",
  "trimis un agent pe Marte să amendeze robotul Curiosity",
  "desenat portretul robot al suspectului cu carioci originale Herlitz",
  "înăbuşit violent un protest paşnic în Piaţa Victoriei",
  "destructurat o reţea de badminton care călca pe iarbă în Cişmigiu",
  "confiscat o praştie artizanală şi 4 proiectile din pietriş lacustru",
  "scris 10 glume bune pentru roastul unui coleg",
  "dus maşina şefului la spălătoria cu fise de peste drum",
  "interogat persoana bănuită că ar fi înfipt zambila",
  "reconstituit traseul fiecărui pasager prins fără bilet în tramvai",
  "triangulat poziţia galaxiei Andromeda",
  "urmărit cu sufletul la gură un sezon întreg din Star Trek: TNG",
  "dezlegat volumul 4 al revistei Integrame Pentru Începători",
  "sunat la teleshopping să comande revoluţionarul Happy Chop",
  "învăţat Luceafărul pe de rost",
  "luat bătaie la table de la un băiat pe nume Briliantu",
  "făcut figuraţie într-o reclamă la alifie pentru amigdale",
  "învăţat limba klingonă pe Duolingo",
  "alcătuit un eseu despre drama intelectualului în romanul interbelic",
  "dat vaca la schimb pe un pumn de fasole, chipurile, magică",
  "ajuns la casa bunicii cu un coş cu merinde",
  "biruit asupra zmeului, cu toate că prinţesa era de fapt în alt castel",
  "terminat campania protoşilor din Starcraft fără coduri",
  "inventat un aparat de zbor care funcţionează doar cu apă",
  "buşit o dronă încercând să filmeze într-o peşteră în Grecia",
  "cerut măriri de salariu",
  "absolvit Medicina şi s-au specializat în neurochirurgie",
  "efectuat o anchetă telefonică pentru localizarea calului maro",
  "făcut un test din revista Bravo şi le-a ieşit că sunt Joey",
  "spart o grămadă de bani pe o schemă piramidală",
  "alunecat pe diferite coji de fructe",
  "găsit căţeluşul pierdut al altui copil",
  "închiriat o hidrobicicletă şi s-au plimbat cu ea",
  "ajutat bătrânica să treacă şoseaua",
  "recuperat telefonul din trompa elefantului de la Zoo",
  "salvat rinocerul de la extincţie",
  "dat milităria jos din pod",
  "oferit flori doamnei învăţătoare",
  "folosit regula de 3 simplă",
  "dat buzna peste un taximetrist şi l-au pus să urmărească acel tramvai",
  "dărâmat o uşă perfect descuiată",
  "prins dihorul care teroriza Avicola din localitate",
  "păcălit un corb să-şi scape caşcavalul din cioc",
  "ajutat la ridicarea Marii Piramide",
  "găsit 2 grame de marihuana în cadrul unui control de rutină",
  "dispersat un grup de satanişti care fumau în uscătoria blocului",
  "tăiat copacul deoarece pisica refuza să coboare",
  "momit pisica pierdută cu o conservă de şprot în ulei",
  "încercat pentru prima oară mâncare chinezească şi le-a plăcut",
  "inspectat raftul de sus cu ajutorul unui scăunel",
  "luat o boală de piele de la ştrand",
  "convins un duh să le îndeplinească patru dorinţe",
  "ieşit la pensie",
  "făcut un grătar de zile mari",
  "construit o şură trainică",
  "organizat un flashmob",
  "dat pisicuţa jos din pom",
];

let fantani = [
  "un aspersor",
  "un robinet",
  "un furtun de grădină",
  "cascada Niagara",
  "o ţâşnitoare",
  "o cişmea",
  "Canalul Dunăre-Marea Neagră",
  "Oltul şi Mureşul la un loc",
  "un bidon cu dopul găurit",
  "o ţeavă spartă",
  "un gheţar afectat de încălzirea globală",
  "un pistol cu apă",
  "o icoană miraculoasă",
  "un ţuţuroi",
  "un hidrant",
  "fântânile de la Unirii",
  "o căprioară rătăcită printre munţi",
  "un sifon",
  "o stropitoare",
  "un pui de focă",
  "maică-ta când se uită la Suleyman Magnificul",
  "o mitralieră de lacrimi",
  "o bocitoare rurală",
  "un smiorcoid de pe planeta Plângton",
  "un dozator TEC",
];

let prajituri = [
  "tort",
  "chec",
  "cozonac",
  "panettone",
  "lava cake",
  "brioşă",
  "fursec",
  "amandină",
  "banană",
  "bomboană",
  "teanc de bani",
  "homar",
  "ghindă",
  "castravete",
  "plăcintă",
  "pateu",
  "cornuleţ cu lapte",
  "drob",
  "porc",
  "parizer",
  "şalău",
  "caşcaval pane",
  "turtă dulce",
  "savarină",
  "broccoli",
  "cernoziom",
  "macrou afumat",
  "murătură",
  "creier măcelăresc",
  "rodie",
  "untură",
  "ceapă",
  "covridog",
  "fosilă",
  "quiche",
  "tartă",
  "gorgonzola",
  "lămâie",
  "mămăligă",
  "caş",
  "magneziu",
  "fontă",
  "ciupercă",
  "triunghi Hochland",
  "crenvurşt",
  "salam săsesc",
  "sărmăluţă",
  "fornetti cu telemea",
  "chupa chups",
  "pâine cu unt",
  "pizza",
];

let sarbatori = [
  "pomana porcului",
  "o postare cu 7000 de likeuri",
  "un selfie",
  "baloane de săpun",
  "un târg de Crăciun în Piaţa Constituţiei",
  "o biserică",
  "un ritual satanic",
  "o vrajă puternică",
  "un chef cu manele",
  "o expediţie la Polul Sud",
  "dovlecei pane cu tzatziki",
  "ţurţuri la nas",
  "o horă",
  "un festival de folk",
  "un talk-show politic",
  "un pas înainte spre comunism",
  "compot",
  "o răscoală ţărănească",
  "o şedinţă cu părinţii",
  "o partidă înflăcărată de macao",
  "o rundă de golf",
  "un turneu de şah",
  "un referendum homofob",
  "un zid de apărare ciclopic",
  "o tură de Herăstrău pe role",
  "etnogeneza poporului român",
  "un referendum homofob",
  "un show aerian",
  "un ceaun de jumări",
  "un recensământ",
  "o tabără de masculinitate",
  "o lecţie de mindfulness",
  "karate",
  "vocalize",
  "un grătar în livadă",
  "ţuică din toate corcoduşele culese pe drum",
  "schimb de id-uri de Yahoo Messenger",
  "cercuri în nisip pentru a-şi dovedi teorema",
  "o serată dansantă",
  "o plimbare pe faleză",
  "plajă până s-au cojit pe nas",
  "o reţetă văzută la Jamila",
  "un scurtmetraj indie în limba daneză",
  "un dulap de la IKEA",
  "schimb de figurine cu ştrumfi",
  "tema de vacanţă la mate",
  "un album techno intitulat POLIZEIARBEIT",
  "bancuri cu soacre",
  "cafeluţă",
  "content pentru canalul de tiktok",
  "concurs de alergat în saci",
];

let felicitari = [
  "Hip, hip, ura!",
  "Bv tată, mari autorităţi!",
  "DURA LEX SED LEX!",
  "Aliluia!",
  "Ura şi la gară!",
  "Cangratulation’s every bode!",
  "La mulţi ani 1997!",
  "Felicitări!",
  "Felikitări!",
  "Trăiască!",
  "Siguranţă şi încredere!",
  "Mazel tov!",
  "Valar morghulis!",
  "La mai mare!",
  "Forza Steaua!",
  "Big up!",
  "Like, share şi subscribe!",
  "Aşa ceva!",
  "Nu ne mai facem bine!",
  "Viaţa fără poezie e greu!",
  "A fi sau a nu fi? Iată întrebarea!",
  "Sau asta vor EI să credem!",
  "A fost o zi minunată!",
  "Un Crăciun de pomină!",
  "Ptiu, ptiu, să nu te deochi!",
  "Cool cool cool!",
  "Cowabunga!",
  "La Vama Veche, în ureche!",
  "Când ne-o fi mai rău, aşa să ne fie!",
  "Şi-am încălecat pe-o şa!",
  "Ecce homo!",
  "Amin!",
  "Numele acelor poliţişti? Albert Einstein.",
  "O, paşă, tu ce darnic eşti!",
  "Şi au trăit fericiţi până la adânci bătrâneţi!",
  "Cine-i născut în ianuarie, hai sus!",
  "Aşa da, şi în nici un caz altfel!",
];

let bodyParts = [
  "nas",
  "frunte",
  "ochi",
  "urechi",
  "ceafă",
  "plexul solar",
  "călcâie",
  "spate",
  "scalp",
  "sprâncene",
  "încheieturi",
  "dinţi",
  "coate",
  "pupile",
  "plămâni",
  "tendonul lui Ahile",
  "obraji",
  "pleoape",
  "subraţ",
  "buze",
];

function getRandomIndex(array) {
  const index = Math.floor(Math.random() * array.length);
  return index;
}

function randomIntFromInterval(min, max) {
  // min and max included
  return Math.floor(Math.random() * (max - min + 1) + min);
}

function handleClick() {
  //nume
  let randomNumeIndex = getRandomIndex(nume);
  updateTextContent("nume", nume[randomNumeIndex]);

  //ocupatie
  updateTextContent("ocupatie", ocupatii[randomNumeIndex]);

  //rudenie
  let randomRudenieIndex = getRandomIndex(rudenii);
  updateTextContent("rudenie", rudenii[randomRudenieIndex]);

  //varsta
  let randomVarsta = randomIntFromInterval(2, 18);
  updateTextContent("varsta", randomVarsta);

  //probleme
  let randomProblemaIndex = getRandomIndex(probleme);
  updateTextContent("problema", probleme[randomProblemaIndex]);

  //fantani
  let randomFantanaIndex = getRandomIndex(fantani);
  updateTextContent("fantana", fantani[randomFantanaIndex]);

  //rezolvari
  let randomRezolvareIndex = getRandomIndex(rezolvari);
  updateTextContent("rezolvare", rezolvari[randomRezolvareIndex]);

  //ore
  let randomOra = randomIntFromInterval(2, 19);
  updateTextContent("timp", randomOra);

  //prajituri
  let randomPrajiIndex = getRandomIndex(prajituri);
  updateTextContent("praji", prajituri[randomPrajiIndex]);

  //sarbatori
  let randomSarbatoareIndex = getRandomIndex(sarbatori);
  updateTextContent("sarbatoare", sarbatori[randomSarbatoareIndex]);

  //anotimpuri
  let randomAnotimpIndex = getRandomIndex(anotimpuri);
  updateTextContent("anotimp", anotimpuri[randomAnotimpIndex]);

  //orase
  let randomOrasIndex = getRandomIndex(orase);
  updateTextContent("oras", orase[randomOrasIndex]);

  //parte a corpului
  let randomBodyIndex = getRandomIndex(bodyParts);
  updateTextContent("partea-corpului", bodyParts[randomBodyIndex]);

  //felicitari
  let randomFelicitareIndex = getRandomIndex(felicitari);
  updateTextContent("felicitari", felicitari[randomFelicitareIndex]);

  //comments
  updateTextContent("num-comments", randomIntFromInterval(147, 11648));

  //laics
  updateTextContent("num-laics", randomIntFromInterval(147, 948));
}

function updateTextContent(dataTarget, value) {
  const elements = document.querySelectorAll(`[data-target="${dataTarget}"]`);
  elements.forEach((element) => {
    element.innerText = value;
  });
}

function likeButton() {
  let graylike = document.querySelector(".like");
  let likes = document.querySelector(".likes-span");
  if (graylike.src.match("images/gray_like.png")) {
    graylike.src = "images/blue_like.png";
    likes.innerHTML = "500";
  } else {
    graylike.src = "images/gray_like.png";
    likes.innerHTML = "499";
  }
}
